# Generated by Django 4.0.6 on 2022-07-24 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Power_Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('local_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('complete', models.BooleanField()),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_socket.power_socket')),
            ],
        ),
    ]
